spring:
  application:
    name: ssdut-forum
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.42.251.254:3306/forum?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: li1259535860
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  port: 8080

swagger:
  enabled: true


#logging:
#  level:
#    root: debug
#  file:
#    name: outofmemory.log
#    developer.outofmemory.dao: debug
#
#mybatis-plus:
#  mapper-locations: classpath:**/*.xml